TOPIC_KEYWORDS: dict[str, list[str]] = {
    "ai": [
        "ai",
        "artificial intelligence",
        "openai",
        "llm",
        "machine learning",
        "neural",
        "chatgpt",
        "model",
        "generative",
        "automation",
    ],
    "tech": [
        "software",
        "startup",
        "github",
        "developer",
        "programming",
        "app",
        "cloud",
        "database",
        "api",
        "python",
        "javascript",
        "platform",
        "product",
        "engineering",
    ],
    "security": [
        "security",
        "cyber",
        "hack",
        "breach",
        "vulnerability",
        "malware",
        "ransomware",
        "exploit",
        "phishing",
        "privacy",
        "data leak",
    ],
    "business": [
        "market",
        "stock",
        "funding",
        "company",
        "business",
        "economy",
        "revenue",
        "profit",
        "startup",
        "acquisition",
        "ipo",
        "layoffs",
    ],
    "world": ["war", "country", "minister", "president", "border", "military", "conflict", "diplomacy", "foreign", "global"],
    "science": ["science", "research", "space", "nasa", "physics", "biology", "chemistry", "study", "experiment", "discovery"],
    "health": ["health", "medicine", "medical", "doctor", "hospital", "disease", "vaccine", "mental health", "fitness", "nutrition"],
    "sports": ["sports", "football", "soccer", "basketball", "tennis", "league", "match", "goal", "coach", "player", "team"],
    "politics": ["election", "government", "parliament", "senate", "congress", "campaign", "vote", "policy", "minister", "president"],
    "finance": ["bank", "interest rate", "inflation", "fed", "central bank", "crypto", "bitcoin", "investment", "bond", "trading", "fund"],
    "climate": ["climate", "weather", "warming", "carbon", "emissions", "renewable", "energy", "solar", "wind", "pollution", "environment"],
    "entertainment": ["movie", "film", "music", "celebrity", "tv", "series", "streaming", "netflix", "hollywood", "game", "gaming"],
}
