TOPIC_KEYWORDS: dict[str, list[str]] = {
    "ai": [
        "ai",
        "artificial intelligence",
        "openai",
        "llm",
        "machine learning",
        "neural",
        "chatgpt",
        "generative",
        "automation",
        "foundation model",
    ],
    "technology": [
        "technology",
        "tech",
        "software",
        "github",
        "developer",
        "programming",
        "app",
        "cloud",
        "database",
        "api",
        "python",
        "javascript",
        "platform",
        "product",
        "engineering",
        "semiconductor",
        "chip",
    ],
    "cybersecurity": [
        "security",
        "cyber",
        "cybersecurity",
        "cyber security",
        "hack",
        "breach",
        "vulnerability",
        "malware",
        "ransomware",
        "exploit",
        "phishing",
        "privacy",
        "data leak",
    ],
    "business": [
        "business",
        "company",
        "revenue",
        "profit",
        "earnings",
        "acquisition",
        "ipo",
        "layoffs",
        "ceo",
        "enterprise",
        "market share",
    ],
    "finance": [
        "finance",
        "bank",
        "interest rate",
        "inflation",
        "fed",
        "central bank",
        "crypto",
        "bitcoin",
        "investment",
        "bond",
        "trading",
        "fund",
        "stock",
        "market",
    ],
    "startups": [
        "startup",
        "startups",
        "founder",
        "venture",
        "vc",
        "seed round",
        "series a",
        "funding",
        "accelerator",
        "pitch deck",
    ],
    "politics": [
        "election",
        "government",
        "parliament",
        "senate",
        "congress",
        "campaign",
        "vote",
        "policy",
        "minister",
        "president",
        "prime minister",
        "lawmakers",
    ],
    "world": [
        "world",
        "global",
        "foreign",
        "war",
        "country",
        "president",
        "minister",
        "border",
        "military",
        "conflict",
        "diplomacy",
        "international",
        "united nations",
    ],
    "israel": [
        "israel",
        "israeli",
        "jerusalem",
        "tel aviv",
        "gaza",
        "hamas",
        "west bank",
        "netanyahu",
        "idf",
    ],
    "science": [
        "science",
        "research",
        "space",
        "nasa",
        "physics",
        "biology",
        "chemistry",
        "study",
        "experiment",
        "discovery",
        "scientists",
    ],
    "health": [
        "health",
        "medicine",
        "medical",
        "doctor",
        "hospital",
        "disease",
        "vaccine",
        "mental health",
        "fitness",
        "nutrition",
        "public health",
    ],
    "climate": [
        "climate",
        "weather",
        "warming",
        "carbon",
        "emissions",
        "renewable",
        "energy",
        "solar",
        "wind",
        "pollution",
        "environment",
        "wildfire",
    ],
    "sports": [
        "sports",
        "league",
        "match",
        "coach",
        "player",
        "team",
        "tournament",
        "championship",
        "score",
        "playoffs",
    ],
    "football": [
        "football",
        "nfl",
        "quarterback",
        "touchdown",
        "premier league",
        "soccer",
        "fifa",
        "goalkeeper",
        "world cup",
    ],
    "basketball": [
        "basketball",
        "nba",
        "wnba",
        "hoops",
        "point guard",
        "three-pointer",
        "playoffs",
        "dunk",
        "lakers",
        "celtics",
    ],
    "tennis": [
        "tennis",
        "wimbledon",
        "grand slam",
        "atp",
        "wta",
        "forehand",
        "backhand",
        "serve",
        "us open",
        "french open",
    ],
    "culture": [
        "culture",
        "books",
        "art",
        "museum",
        "theater",
        "theatre",
        "literature",
        "festival",
        "opera",
    ],
    "entertainment": [
        "entertainment",
        "movie",
        "film",
        "music",
        "celebrity",
        "tv",
        "series",
        "streaming",
        "netflix",
        "hollywood",
        "box office",
    ],
    "gaming": [
        "gaming",
        "video game",
        "game studio",
        "playstation",
        "xbox",
        "nintendo",
        "steam",
        "esports",
        "twitch",
        "console",
    ],
}
